
name: test and Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Hola mundo"
        run: echo "Hello,word"
      - name: fecha 
        run: date 
      - name: muestrame el contenido del directorio 
        run: ls - la